GENESIS_PLUS_GX_SYSTEM_HW_LABEL "System Hardware"
GENESIS_PLUS_GX_SYSTEM_HW_INFO_0 "Runs loaded content with a specific emulated console. 'Auto' will select the most appropriate system for the current game."
OPTION_VAL_AUTO "Auto"
OPTION_VAL_SG_1000 "SG-1000"
OPTION_VAL_SG_1000_II "SG-1000 II"
OPTION_VAL_MARK_III "Mark III"
OPTION_VAL_MASTER_SYSTEM "Master System"
OPTION_VAL_MASTER_SYSTEM_II "Master System II"
OPTION_VAL_GAME_GEAR "Game Gear"
OPTION_VAL_MEGA_DRIVE_GENESIS "Mega Drive/Genesis"
GENESIS_PLUS_GX_REGION_DETECT_LABEL "System Region"
GENESIS_PLUS_GX_REGION_DETECT_INFO_0 "Specify which region the system is from. For consoles other than the Game Gear, 'PAL' is 50hz while 'NTSC' is 60hz. Games may run faster or slower than normal if the incorrect region is selected."
OPTION_VAL_NTSC_U "NTSC-U"
OPTION_VAL_PAL "PAL"
OPTION_VAL_NTSC_J "NTSC-J"
GENESIS_PLUS_GX_FORCE_DTACK_LABEL "System Lock-Ups"
GENESIS_PLUS_GX_FORCE_DTACK_INFO_0 "Emulate system lock-ups that occur on real hardware when performing illegal address access. This should only be disabled when playing certain demos and homebrew that rely on illegal behaviour for correct operation."
GENESIS_PLUS_GX_BIOS_LABEL "System Boot ROM"
GENESIS_PLUS_GX_BIOS_INFO_0 "Use official BIOS/bootloader for emulated hardware, if present in RetroArch's system directory. Displays console-specific start-up sequence/animation, then runs loaded content."
GENESIS_PLUS_GX_BRAM_LABEL "CD System BRAM"
GENESIS_PLUS_GX_BRAM_INFO_0 "When running Sega CD content, specifies whether to share a single save file between all games from a specific region (Per-BIOS) or to create a separate save file for each game (Per-Game). Note that the Sega CD has limited internal storage, sufficient only for a handful of titles. To avoid running out of space, the 'Per-Game' setting is recommended."
OPTION_VAL_PER_BIOS "Per-BIOS"
OPTION_VAL_PER_GAME "Per-Game"
GENESIS_PLUS_GX_ADDR_ERROR_LABEL "68K Address Error"
GENESIS_PLUS_GX_ADDR_ERROR_INFO_0 "The Genesis CPU (Motorola 68000) produces an Address Error (crash) when attempting to perform unaligned memory access. Enabling '68K Address Error' simulates this behaviour. It should only be disabled when playing ROM hacks, since these are typically developed using less accurate emulators and may rely on invalid RAM access for correct operation."
GENESIS_PLUS_GX_LOCK_ON_LABEL "Cartridge Lock-On"
GENESIS_PLUS_GX_LOCK_ON_INFO_0 "Lock-On Technology is a Genesis feature that allowed an older game to connect to the pass-through port of a special cartridge for extended or altered gameplay. This option specifies which type of special 'lock-on' cartridge to emulate. A corresponding bios file must be present in RetroArch's system directory."
OPTION_VAL_GAME_GENIE "Game Genie"
OPTION_VAL_ACTION_REPLAY_PRO "Action Replay (Pro)"
OPTION_VAL_SONIC_KNUCKLES "Sonic & Knuckles"
GENESIS_PLUS_GX_YM2413_LABEL "Master System FM (YM2413)"
GENESIS_PLUS_GX_YM2413_INFO_0 "Enable emulation of the FM Sound Unit used by certain Sega Mark III/Master System games for enhanced audio output."
GENESIS_PLUS_GX_YM2612_LABEL "Mega Drive / Genesis FM"
GENESIS_PLUS_GX_YM2612_INFO_0 "Select method used to emulate the FM synthesizer (main sound generator) of the Mega Drive/Genesis. 'MAME' options are fast, and run full speed on most systems. 'Nuked' options are cycle accurate, very high quality, and have substantial CPU requirements. The 'YM2612' chip is used by the original Model 1 Genesis. The 'YM3438' is used in later Genesis revisions."
GENESIS_PLUS_GX_YM2612_INFO_1 "Select method used to emulate the FM synthesizer (main sound generator) of the Mega Drive/Genesis. The 'YM2612' chip is used by the original Model 1 Genesis. The 'YM3438' is used in later Genesis revisions."
OPTION_VAL_MAME_YM2612 "MAME (YM2612)"
OPTION_VAL_MAME_ASIC_YM3438 "MAME (ASIC YM3438)"
OPTION_VAL_MAME_ENHANCED_YM3438 "MAME (Enhanced YM3438)"
OPTION_VAL_NUKED_YM2612 "Nuked (YM2612)"
OPTION_VAL_NUKED_YM3438 "Nuked (YM3438)"
GENESIS_PLUS_GX_SOUND_OUTPUT_LABEL "Sound Output"
GENESIS_PLUS_GX_SOUND_OUTPUT_INFO_0 "Select stereo or mono sound reproduction."
OPTION_VAL_STEREO "Stereo"
OPTION_VAL_MONO "Mono"
GENESIS_PLUS_GX_PSG_PREAMP_LABEL "PSG Preamp Level"
GENESIS_PLUS_GX_PSG_PREAMP_INFO_0 "Set the audio preamplifier level of the emulated SN76496 4-channel Programmable Sound Generator found in the Master System, Game Gear and Genesis."
GENESIS_PLUS_GX_FM_PREAMP_LABEL "FM Preamp Level"
GENESIS_PLUS_GX_FM_PREAMP_INFO_0 "Set the audio preamplifier level of the emulated Sega Mark III/Master System FM Sound Unit."
GENESIS_PLUS_GX_AUDIO_FILTER_LABEL "Audio Filter"
GENESIS_PLUS_GX_AUDIO_FILTER_INFO_0 "Enable a low pass audio filter to better simulate the characteristic sound of a Model 1 Genesis."
OPTION_VAL_LOW_PASS "Low-Pass"
GENESIS_PLUS_GX_LOWPASS_RANGE_LABEL "Low-Pass Filter %"
GENESIS_PLUS_GX_LOWPASS_RANGE_INFO_0 "Specify the cut-off frequency of the audio low pass filter. A higher value increases the perceived 'strength' of the filter, since a wider range of the high frequency spectrum is attenuated."
GENESIS_PLUS_GX_AUDIO_EQ_LOW_LABEL "EQ Low"
GENESIS_PLUS_GX_AUDIO_EQ_LOW_INFO_0 "Adjust the low range band of the internal audio equaliser."
GENESIS_PLUS_GX_AUDIO_EQ_MID_LABEL "EQ Mid"
GENESIS_PLUS_GX_AUDIO_EQ_MID_INFO_0 "Adjust the middle range band of the internal audio equaliser."
GENESIS_PLUS_GX_AUDIO_EQ_HIGH_LABEL "EQ High"
GENESIS_PLUS_GX_AUDIO_EQ_HIGH_INFO_0 "Adjust the high range band of the internal audio equaliser."
GENESIS_PLUS_GX_FRAMESKIP_LABEL "Frameskip"
GENESIS_PLUS_GX_FRAMESKIP_INFO_0 "Skip frames to avoid audio buffer under-run (crackling). Improves performance at the expense of visual smoothness. 'Auto' skips frames when advised by the frontend. 'Manual' utilises the 'Frameskip Threshold (%)' setting."
OPTION_VAL_MANUAL "Manual"
GENESIS_PLUS_GX_FRAMESKIP_THRESHOLD_LABEL "Frameskip Threshold (%)"
GENESIS_PLUS_GX_FRAMESKIP_THRESHOLD_INFO_0 "When 'Frameskip' is set to 'Manual', specifies the audio buffer occupancy threshold (percentage) below which frames will be skipped. Higher values reduce the risk of crackling by causing frames to be dropped more frequently."
GENESIS_PLUS_GX_BLARGG_NTSC_FILTER_LABEL "Blargg NTSC Filter"
GENESIS_PLUS_GX_BLARGG_NTSC_FILTER_INFO_0 "Apply a video filter to mimic various NTSC TV signals."
OPTION_VAL_MONOCHROME "Monochrome"
OPTION_VAL_COMPOSITE "Composite"
OPTION_VAL_SVIDEO "S-Video"
OPTION_VAL_RGB "RGB"
GENESIS_PLUS_GX_LCD_FILTER_LABEL "LCD Ghosting Filter"
GENESIS_PLUS_GX_LCD_FILTER_INFO_0 "Apply an image 'ghosting' filter to mimic the display characteristics of the Game Gear and 'Genesis Nomad' LCD panels."
GENESIS_PLUS_GX_OVERSCAN_LABEL "Borders"
GENESIS_PLUS_GX_OVERSCAN_INFO_0 "Enable this to display the overscan regions at the top/bottom and/or left/right of the screen. These would normally be hidden by the bezel around the edge of a standard-definition television."
OPTION_VAL_TOP_BOTTOM "Top/Bottom"
OPTION_VAL_LEFT_RIGHT "Left/Right"
OPTION_VAL_FULL "Full"
GENESIS_PLUS_GX_GG_EXTRA_LABEL "Game Gear Extended Screen"
GENESIS_PLUS_GX_GG_EXTRA_INFO_0 "Forces Game Gear titles to run in 'SMS' mode, with an increased resolution of 256x192. May show additional content, but typically displays a border of corrupt/unwanted image data."
GENESIS_PLUS_GX_LEFT_BORDER_LABEL "Hide Master System Left Border"
GENESIS_PLUS_GX_LEFT_BORDER_INFO_0 "Cuts off 8 pixels from both the left and right side of the screen when running Master System games, thereby hiding the border seen on the left side of the screen"
GENESIS_PLUS_GX_ASPECT_RATIO_LABEL "Core-Provided Aspect Ratio"
GENESIS_PLUS_GX_ASPECT_RATIO_INFO_0 "Choose the preferred content aspect ratio. This will only apply when RetroArch's aspect ratio is set to 'Core provided' in the Video settings."
OPTION_VAL_NTSC_PAR "NTSC PAR"
OPTION_VAL_PAL_PAR "PAL PAR"
GENESIS_PLUS_GX_RENDER_LABEL "Interlaced Mode 2 Output"
GENESIS_PLUS_GX_RENDER_INFO_0 "Interlaced Mode 2 allows the Genesis to output a double height (high resolution) 320x448 image by drawing alternate scanlines each frame (this is used by 'Sonic the Hedgehog 2' and 'Combat Cars' multiplayer modes). 'Double Field' mimics original hardware, producing a sharp image with flickering/interlacing artefacts. 'Single Field' apples a de-interlacing filter, which stabilises the image but causes mild blurring."
OPTION_VAL_SINGLE_FIELD "Single Field"
OPTION_VAL_DOUBLE_FIELD "Double Field"
GENESIS_PLUS_GX_GUN_CURSOR_LABEL "Show Light Gun Crosshair"
GENESIS_PLUS_GX_GUN_CURSOR_INFO_0 "Display light gun crosshairs when using the 'MD Menacer', 'MD Justifiers' and 'MS Light Phaser' input device types."
GENESIS_PLUS_GX_GUN_INPUT_LABEL "Light Gun Input"
GENESIS_PLUS_GX_GUN_INPUT_INFO_0 "Use a mouse-controlled 'Light Gun' or 'Touchscreen' input."
OPTION_VAL_LIGHTGUN "Light Gun"
OPTION_VAL_TOUCHSCREEN "Touchscreen"
GENESIS_PLUS_GX_INVERT_MOUSE_LABEL "Invert Mouse Y-Axis"
GENESIS_PLUS_GX_INVERT_MOUSE_INFO_0 "Inverts the Y-axis of the 'MD Mouse' input device type."
GENESIS_PLUS_GX_OVERCLOCK_LABEL "CPU Speed"
GENESIS_PLUS_GX_OVERCLOCK_INFO_0 "Overclock the emulated CPU. Can reduce slowdown, but may cause glitches."
OPTION_VAL_100 "100%"
OPTION_VAL_125 "125%"
OPTION_VAL_150 "150%"
OPTION_VAL_175 "175%"
OPTION_VAL_200 "200%"
GENESIS_PLUS_GX_NO_SPRITE_LIMIT_LABEL "Remove Per-Line Sprite Limit"
GENESIS_PLUS_GX_NO_SPRITE_LIMIT_INFO_0 "Removes the 8 (Master System) or 20 (Genesis) sprite-per-scanline hardware limit. This reduces flickering but can cause visual glitches, as some games exploit the hardware limit to generate special effects."
GENESIS_PLUS_GX_SHOW_ADVANCED_AUDIO_SETTINGS_LABEL "Show Advanced Audio Volume Settings (Reopen menu)"
GENESIS_PLUS_GX_SHOW_ADVANCED_AUDIO_SETTINGS_INFO_0 "Enable configuration of low-level audio channel parameters. NOTE: Quick Menu must be toggled for this setting to take effect."
GENESIS_PLUS_GX_PSG_CHANNEL_0_VOLUME_LABEL "PSG Tone Channel 0 Volume %"
GENESIS_PLUS_GX_PSG_CHANNEL_0_VOLUME_INFO_0 "Reduce the volume of the PSG Tone Channel 0."
GENESIS_PLUS_GX_PSG_CHANNEL_1_VOLUME_LABEL "PSG Tone Channel 1 Volume %"
GENESIS_PLUS_GX_PSG_CHANNEL_1_VOLUME_INFO_0 "Reduce the volume of the PSG Tone Channel 1."
GENESIS_PLUS_GX_PSG_CHANNEL_2_VOLUME_LABEL "PSG Tone Channel 2 Volume %"
GENESIS_PLUS_GX_PSG_CHANNEL_2_VOLUME_INFO_0 "Reduce the volume of the PSG Tone Channel 2."
GENESIS_PLUS_GX_PSG_CHANNEL_3_VOLUME_LABEL "PSG Noise Channel 3 Volume %"
GENESIS_PLUS_GX_PSG_CHANNEL_3_VOLUME_INFO_0 "Reduce the volume of the PSG Noise Channel 3."
GENESIS_PLUS_GX_MD_CHANNEL_0_VOLUME_LABEL "Mega Drive / Genesis FM Channel 0 Volume %"
GENESIS_PLUS_GX_MD_CHANNEL_0_VOLUME_INFO_0 "Reduce the volume of the Mega Drive / Genesis FM Channel 0. Only works with MAME FM emulators."
GENESIS_PLUS_GX_MD_CHANNEL_1_VOLUME_LABEL "Mega Drive / Genesis FM Channel 1 Volume %"
GENESIS_PLUS_GX_MD_CHANNEL_1_VOLUME_INFO_0 "Reduce the volume of the Mega Drive / Genesis FM Channel 1. Only works with MAME FM emulators."
GENESIS_PLUS_GX_MD_CHANNEL_2_VOLUME_LABEL "Mega Drive / Genesis FM Channel 2 Volume %"
GENESIS_PLUS_GX_MD_CHANNEL_2_VOLUME_INFO_0 "Reduce the volume of the Mega Drive / Genesis FM Channel 2. Only works with MAME FM emulators."
GENESIS_PLUS_GX_MD_CHANNEL_3_VOLUME_LABEL "Mega Drive / Genesis FM Channel 3 Volume %"
GENESIS_PLUS_GX_MD_CHANNEL_3_VOLUME_INFO_0 "Reduce the volume of the Mega Drive / Genesis FM Channel 3. Only works with MAME FM emulators."
GENESIS_PLUS_GX_MD_CHANNEL_4_VOLUME_LABEL "Mega Drive / Genesis FM Channel 4 Volume %"
GENESIS_PLUS_GX_MD_CHANNEL_4_VOLUME_INFO_0 "Reduce the volume of the Mega Drive / Genesis FM Channel 4. Only works with MAME FM emulators."
GENESIS_PLUS_GX_MD_CHANNEL_5_VOLUME_LABEL "Mega Drive / Genesis FM Channel 5 Volume %"
GENESIS_PLUS_GX_MD_CHANNEL_5_VOLUME_INFO_0 "Reduce the volume of the Mega Drive / Genesis FM Channel 5. Only works with MAME FM emulators."
GENESIS_PLUS_GX_SMS_FM_CHANNEL_0_VOLUME_LABEL "Master System FM (YM2413) Channel 0 Volume %"
GENESIS_PLUS_GX_SMS_FM_CHANNEL_0_VOLUME_INFO_0 "Reduce the volume of the Master System FM Channel 0."
GENESIS_PLUS_GX_SMS_FM_CHANNEL_1_VOLUME_LABEL "Master System FM (YM2413) Channel 1 Volume %"
GENESIS_PLUS_GX_SMS_FM_CHANNEL_1_VOLUME_INFO_0 "Reduce the volume of the Master System FM Channel 1."
GENESIS_PLUS_GX_SMS_FM_CHANNEL_2_VOLUME_LABEL "Master System FM (YM2413) Channel 2 Volume %"
GENESIS_PLUS_GX_SMS_FM_CHANNEL_2_VOLUME_INFO_0 "Reduce the volume of the Master System FM Channel 2."
GENESIS_PLUS_GX_SMS_FM_CHANNEL_3_VOLUME_LABEL "Master System FM (YM2413) Channel 3 Volume %"
GENESIS_PLUS_GX_SMS_FM_CHANNEL_3_VOLUME_INFO_0 "Reduce the volume of the Master System FM Channel 3."
GENESIS_PLUS_GX_SMS_FM_CHANNEL_4_VOLUME_LABEL "Master System FM (YM2413) Channel 4 Volume %"
GENESIS_PLUS_GX_SMS_FM_CHANNEL_4_VOLUME_INFO_0 "Reduce the volume of the Master System FM Channel 4."
GENESIS_PLUS_GX_SMS_FM_CHANNEL_5_VOLUME_LABEL "Master System FM (YM2413) Channel 5 Volume %"
GENESIS_PLUS_GX_SMS_FM_CHANNEL_5_VOLUME_INFO_0 "Reduce the volume of the Master System FM Channel 5."
GENESIS_PLUS_GX_SMS_FM_CHANNEL_6_VOLUME_LABEL "Master System FM (YM2413) Channel 6 Volume %"
GENESIS_PLUS_GX_SMS_FM_CHANNEL_6_VOLUME_INFO_0 "Reduce the volume of the Master System FM Channel 6."
GENESIS_PLUS_GX_SMS_FM_CHANNEL_7_VOLUME_LABEL "Master System FM (YM2413) Channel 7 Volume %"
GENESIS_PLUS_GX_SMS_FM_CHANNEL_7_VOLUME_INFO_0 "Reduce the volume of the Master System FM Channel 7."
GENESIS_PLUS_GX_SMS_FM_CHANNEL_8_VOLUME_LABEL "Master System FM (YM2413) Channel 8 Volume %"
GENESIS_PLUS_GX_SMS_FM_CHANNEL_8_VOLUME_INFO_0 "Reduce the volume of the Master System FM Channel 8."
