GENESIS_PLUS_GX_SYSTEM_HW_LABEL "Hardware do sistema"
GENESIS_PLUS_GX_SYSTEM_HW_INFO_0 "Executa o conteúdo carregado com um console emulado específico. 'Automático' selecionará o sistema mais apropriado para o jogo atual."
OPTION_VAL_AUTO "auto"
OPTION_VAL_SG_1000 "SG-1000"
OPTION_VAL_SG_1000_II "SG-1000 II"
OPTION_VAL_MARK_III "Mark III"
OPTION_VAL_MASTER_SYSTEM "Master System"
OPTION_VAL_MASTER_SYSTEM_II "Master System II"
OPTION_VAL_GAME_GEAR "Game Gear"
OPTION_VAL_MEGA_DRIVE_GENESIS "Mega Drive"
GENESIS_PLUS_GX_REGION_DETECT_LABEL "Região do sistema"
GENESIS_PLUS_GX_REGION_DETECT_INFO_0 "Especifica de que região o sistema é. Para consoles que não sejam o Game Gear, 'PAL' é de 50hz enquanto 'NTSC' é de 60hz. s jogos podem ser executados mais rapidamente ou mais lentamente do que o normal se a região incorreta estiver selecionada."
OPTION_VAL_NTSC_U "NTSC-U"
OPTION_VAL_PAL "PAL"
OPTION_VAL_NTSC_J "NTSC-J"
GENESIS_PLUS_GX_FORCE_DTACK_LABEL "Bloqueios do sistema"
GENESIS_PLUS_GX_FORCE_DTACK_INFO_0 "Emula os bloqueios do sistema que ocorrem no hardware real ao executar acesso ilegal a endereços. Isso só deve ser desativado ao reproduzir certas demos e homebrews que dependem de comportamento ilegal para a operação correta."
GENESIS_PLUS_GX_BIOS_LABEL "ROM de inicialização do sistema"
GENESIS_PLUS_GX_BIOS_INFO_0 "Usa a BIOS/bootloader oficial para o hardware emulado, se estiver presente no diretório de sistema do RetroArch. Exibe a sequência/animação da inicialização específica do console e executa o conteúdo carregado."
GENESIS_PLUS_GX_BRAM_LABEL "Sistema BRAM do CD"
GENESIS_PLUS_GX_BRAM_INFO_0 "Ao executar o conteúdo de CD da Sega, especifica se um único arquivo salvo será salvo entre todos os jogos de uma região específica (Por-BIOS) ou se será criado um arquivo salvo separado para cada jogo (Por-Jogo). Observe que o CD da Sega possui armazenamento interno limitado, suficiente apenas para alguns títulos. Para evitar ficar sem espaço, a configuração 'Por jogo' é recomendada."
OPTION_VAL_PER_BIOS "Por-BIOS"
OPTION_VAL_PER_GAME "Por-Jogo"
GENESIS_PLUS_GX_ADDR_ERROR_LABEL "Erro de endereçamento do 68K"
GENESIS_PLUS_GX_ADDR_ERROR_INFO_0 "A CPU do Mega Drive (Motorola 68000) produz um erro de endereçamento (falha) ao tentar executar o acesso desalinhado à memória. A ativação do 'Erro de endereçamento do 68K' simula esse comportamento. Ele deve ser desativado apenas durante a execução de hacks de ROMs, pois geralmente são desenvolvidos usando emuladores menos precisos e podem contar com acesso inválido à RAM para a operação correta."
GENESIS_PLUS_GX_LOCK_ON_LABEL "Cartucho Lock-On"
GENESIS_PLUS_GX_LOCK_ON_INFO_0 "A tecnologia Lock-On é um recurso do Mega Drive que permite que um jogo mais antigo se conecte à porta de passagem de um cartucho especial para uma jogabilidade estendida ou alterada. Esta opção especifica qual tipo de cartucho especial 'lock-on' a ser emulado. Um arquivo do BIOS correspondente deve estar presente no diretório do sistema do RetroArch."
OPTION_VAL_GAME_GENIE "Game Genie"
OPTION_VAL_ACTION_REPLAY_PRO "Action Replay (Pro)"
OPTION_VAL_SONIC_KNUCKLES "Sonic & Knuckles"
GENESIS_PLUS_GX_YM2413_LABEL "Som FM do Master System (YM2413)"
GENESIS_PLUS_GX_YM2413_INFO_0 "Ativa a emulação da unidade de som FM usada por certos jogos do Master System para obter uma saída de áudio aprimorada."
GENESIS_PLUS_GX_YM2612_LABEL "Som FM do Mega Drive"
GENESIS_PLUS_GX_YM2612_INFO_0 "Seleciona o método usado para emular o sintetizador FM (gerador de som principal) do Mega Drive. As opções 'MAME' são rápidas e executam a toda velocidade na maioria dos sistemas. As opções 'Nuked' têm precisão de ciclo, qualidade muito alta e requisitos substanciais de CPU. O chip 'YM2612' é usado pelo Mega Drive Modelo 1 original. O 'YM3438' é usado em revisões posteriores do Mega Drive."
GENESIS_PLUS_GX_YM2612_INFO_1 "Seleciona o método usado para emular o sintetizador de FM (gerador de som principal) do Mega Drive. O chip 'YM2612' é usado pelo Mega Drive Modelo 1 original. O 'YM3438' é usado em revisões posteriores do Mega Drive."
OPTION_VAL_MAME_YM2612 "MAME (YM2612)"
OPTION_VAL_MAME_ASIC_YM3438 "MAME (ASIC YM3438)"
OPTION_VAL_MAME_ENHANCED_YM3438 "MAME (YM3438 aprimorado)"
OPTION_VAL_NUKED_YM2612 "Nuked (YM2612)"
OPTION_VAL_NUKED_YM3438 "Nuked (YM3438)"
GENESIS_PLUS_GX_SOUND_OUTPUT_LABEL "Saída de som"
GENESIS_PLUS_GX_SOUND_OUTPUT_INFO_0 "Selecione reprodução de som estéreo ou mono."
OPTION_VAL_STEREO "Estéreo"
OPTION_VAL_MONO "Mono"
GENESIS_PLUS_GX_PSG_PREAMP_LABEL "Nível de pré-amplificação do PSG"
GENESIS_PLUS_GX_PSG_PREAMP_INFO_0 "Define o nível de pré-amplificação do áudio do Gerador de Som Programável (PSG) de 4 canais SN76496 emulado encontrado no Master System, Game Gear e Mega Drive."
GENESIS_PLUS_GX_FM_PREAMP_LABEL "Nível de pré-amplificação do FM"
GENESIS_PLUS_GX_FM_PREAMP_INFO_0 "Define o nível de pré-amplificação de áudio da Unidade de Som FM emulada do Master System."
GENESIS_PLUS_GX_AUDIO_FILTER_LABEL "Filtro de áudio"
GENESIS_PLUS_GX_AUDIO_FILTER_INFO_0 "Ativa um filtro de áudio passa-baixo para simular melhor o som característico de um Mega Drive Modelo 1."
OPTION_VAL_LOW_PASS "Passa-baixo"
GENESIS_PLUS_GX_LOWPASS_RANGE_LABEL "Filtro passa-baixo %"
GENESIS_PLUS_GX_LOWPASS_RANGE_INFO_0 "Especifica a frequência de corte do filtro de áudio passa-baixo. Um valor mais alto aumenta a 'força' percebida do filtro, uma vez que uma faixa mais ampla do espectro de alta frequência é atenuada."
GENESIS_PLUS_GX_AUDIO_EQ_LOW_LABEL "EQ baixa"
GENESIS_PLUS_GX_AUDIO_EQ_LOW_INFO_0 "Ajuste a banda de alcance baixo do equalizador de áudio interno."
GENESIS_PLUS_GX_AUDIO_EQ_MID_LABEL "EQ média"
GENESIS_PLUS_GX_AUDIO_EQ_MID_INFO_0 "Ajuste a banda de alcance média do equalizador de áudio interno."
GENESIS_PLUS_GX_AUDIO_EQ_HIGH_LABEL "EQ alta"
GENESIS_PLUS_GX_AUDIO_EQ_HIGH_INFO_0 "Ajuste a banda de alcance alta do equalizador de áudio interno."
GENESIS_PLUS_GX_FRAMESKIP_LABEL "Pulo de quadro"
GENESIS_PLUS_GX_FRAMESKIP_INFO_0 "Pula quadros para evitar subexecução do buffer de áudio (estalos). Melhora o desempenho em detrimento da suavidade visual. 'Auto' pula os quadros quando aconselhado pela interface. 'Manual' utiliza a configuração 'Limite de pulo de quadro (%)."
GENESIS_PLUS_GX_FRAMESKIP_THRESHOLD_LABEL "Limite de pulo de quadro (%)"
GENESIS_PLUS_GX_FRAMESKIP_THRESHOLD_INFO_0 "Quando 'Pulo de quadro' é definido como 'Manual', especifica o limite de ocupação do buffer de áudio (porcentagem) abaixo do qual os quadros serão ignorados. Valores mais altos reduzem o risco de estalos, fazendo com que os quadros sejam suprimidos com mais frequência."
GENESIS_PLUS_GX_BLARGG_NTSC_FILTER_LABEL "Filtro Blargg NTSC"
GENESIS_PLUS_GX_BLARGG_NTSC_FILTER_INFO_0 "Aplica um filtro de vídeo para imitar vários sinais de TV NTSC."
OPTION_VAL_MONOCHROME "Monocromático"
OPTION_VAL_COMPOSITE "Composto"
OPTION_VAL_SVIDEO "S-Video"
OPTION_VAL_RGB "RGB"
GENESIS_PLUS_GX_LCD_FILTER_LABEL "Filtro fantasma LCD"
GENESIS_PLUS_GX_LCD_FILTER_INFO_0 "Aplica um filtro de imagem fantasma para imitar as características de exibição dos painéis de LCD do Game Gear e do 'Genesis Nomad'."
GENESIS_PLUS_GX_OVERSCAN_LABEL "Bordas"
GENESIS_PLUS_GX_OVERSCAN_INFO_0 "Ative esta opção para exibir as regiões de overscan na parte superior/inferior e/ou esquerda/direita da tela. Normalmente, seriam ocultas pelo painel ao redor da borda de uma televisão de definição padrão."
OPTION_VAL_TOP_BOTTOM "Superior/inferior"
OPTION_VAL_LEFT_RIGHT "Esquerda/direita"
OPTION_VAL_FULL "Completa"
GENESIS_PLUS_GX_GG_EXTRA_LABEL "Tela estendida do Game Gear"
GENESIS_PLUS_GX_GG_EXTRA_INFO_0 "Força os títulos do Game Gear a serem executados no modo 'SMS', com uma resolução aumentada de 256x192. Pode mostrar conteúdo adicional, mas geralmente exibe uma borda de dados corrompidos/indesejados de imagem."
GENESIS_PLUS_GX_LEFT_BORDER_LABEL "Ocultar borda esquerda do Master System"
GENESIS_PLUS_GX_LEFT_BORDER_INFO_0 "Corta 8 pixels do lado esquerdo e direito da tela ao executar os jogos do Master System, ocultando assim a borda vista no lado esquerdo da tela"
GENESIS_PLUS_GX_ASPECT_RATIO_LABEL "Proporção de aspecto fornecida pelo núcleo"
GENESIS_PLUS_GX_ASPECT_RATIO_INFO_0 "Escolhe a proporção preferida do conteúdo. Isso se aplicará somente quando a proporção do RetroArch estiver configurada como 'Core provided' nas configurações de vídeo."
OPTION_VAL_NTSC_PAR "NTSC PAR"
OPTION_VAL_PAL_PAR "PAL PAR"
GENESIS_PLUS_GX_RENDER_LABEL "Saída entrelaçada modo 2"
GENESIS_PLUS_GX_RENDER_INFO_0 "O Modo entrelaçado 2 permite que o Mega Drive produza uma imagem de 320x448 de altura dupla (alta resolução) desenhando linhas de varredura alternativas em cada quadro (isso é usado pelos modos multijogador do 'Sonic the Hedgehog 2' e 'Combat Cars'). O 'Campo duplo' imita o hardware original, produzindo uma imagem nítida com artefatos trêmulos/entrelaçados. O 'Campo único' é um filtro de desentrelaçamento, que estabiliza a imagem, mas causa desfoque suave."
OPTION_VAL_SINGLE_FIELD "Campo único"
OPTION_VAL_DOUBLE_FIELD "Campo duplo"
GENESIS_PLUS_GX_GUN_CURSOR_LABEL "Mostrar mira da pistola"
GENESIS_PLUS_GX_GUN_CURSOR_INFO_0 "Exibe a mira da pistola de luz ao usar os tipos de dispositivo de entrada 'MD Menacer', 'MD Justifiers' e 'MS Light Phaser'."
GENESIS_PLUS_GX_GUN_INPUT_LABEL "Saída da Pistola de luz"
GENESIS_PLUS_GX_GUN_INPUT_INFO_0 "Usa uma entrada 'Pistola de luz' ou 'Toque na tela' controlada por mouse."
OPTION_VAL_LIGHTGUN "Pistola de luz"
OPTION_VAL_TOUCHSCREEN "Toque na tela"
GENESIS_PLUS_GX_INVERT_MOUSE_LABEL "Inverter eixo Y do mouse"
GENESIS_PLUS_GX_INVERT_MOUSE_INFO_0 "Inverte o eixo Y do tipo de dispositivo de entrada 'MD Mouse'."
GENESIS_PLUS_GX_OVERCLOCK_LABEL "Velocidade da CPU"
GENESIS_PLUS_GX_OVERCLOCK_INFO_0 "Faz um overclock da CPU emulada. Pode reduzir a desaceleração, mas pode causar falhas."
GENESIS_PLUS_GX_NO_SPRITE_LIMIT_LABEL "Remover limite de sprite por linha"
GENESIS_PLUS_GX_NO_SPRITE_LIMIT_INFO_0 "Remove o limite de sprite por varredura do hardware, 8 (Master System) ou 20 (Mega Drive). Isso reduz a tremulação (flickering), mas pode causar falhas visuais, pois alguns jogos exploram o limite de hardware para gerar efeitos especiais."
GENESIS_PLUS_GX_SHOW_ADVANCED_AUDIO_SETTINGS_LABEL "Mostrar configurações avançadas de volume de áudio (reabrir menu)"
GENESIS_PLUS_GX_SHOW_ADVANCED_AUDIO_SETTINGS_INFO_0 "Ativa a configuração dos parâmetros do canal de áudio de baixo nível. NOTA: O Menu rápido deve ser alternado para que esta configuração tenha efeito."
GENESIS_PLUS_GX_PSG_CHANNEL_0_VOLUME_LABEL "% do volume do tom do PSG do canal 0"
GENESIS_PLUS_GX_PSG_CHANNEL_0_VOLUME_INFO_0 "Reduz o volume do tom PSG do canal 0."
GENESIS_PLUS_GX_PSG_CHANNEL_1_VOLUME_LABEL "% do volume do tom do PSG do canal 1"
GENESIS_PLUS_GX_PSG_CHANNEL_1_VOLUME_INFO_0 "Reduz o volume do tom PSG do canal 1."
GENESIS_PLUS_GX_PSG_CHANNEL_2_VOLUME_LABEL "% do volume do tom do PSG do canal 2"
GENESIS_PLUS_GX_PSG_CHANNEL_2_VOLUME_INFO_0 "Reduz o volume do tom PSG do canal 2."
GENESIS_PLUS_GX_PSG_CHANNEL_3_VOLUME_LABEL "% do volume de ruído do PSG do canal 3"
GENESIS_PLUS_GX_PSG_CHANNEL_3_VOLUME_INFO_0 "Reduz o volume do ruído do PSG do canal 3."
GENESIS_PLUS_GX_MD_CHANNEL_0_VOLUME_LABEL "% do volume do FM do Mega Drive do canal 0"
GENESIS_PLUS_GX_MD_CHANNEL_0_VOLUME_INFO_0 "Reduz o volume do FM do Mega Drive do canal 0. Só funciona com o emulador de FM do MAME."
GENESIS_PLUS_GX_MD_CHANNEL_1_VOLUME_LABEL "% do volume do FM do Mega Drive do canal 1"
GENESIS_PLUS_GX_MD_CHANNEL_1_VOLUME_INFO_0 "Reduz o volume do FM do Mega Drive do canal 1. Só funciona com o emulador de FM do MAME."
GENESIS_PLUS_GX_MD_CHANNEL_2_VOLUME_LABEL "% do volume do FM do Mega Drive do canal 2"
GENESIS_PLUS_GX_MD_CHANNEL_2_VOLUME_INFO_0 "Reduz o volume do FM do Mega Drive do canal 2. Só funciona com o emulador de FM do MAME."
GENESIS_PLUS_GX_MD_CHANNEL_3_VOLUME_LABEL "% do volume do FM do Mega Drive do canal 3"
GENESIS_PLUS_GX_MD_CHANNEL_3_VOLUME_INFO_0 "Reduz o volume do FM do Mega Drive do canal 3. Só funciona com o emulador de FM do MAME."
GENESIS_PLUS_GX_MD_CHANNEL_4_VOLUME_LABEL "% do volume do FM do Mega Drive do canal 4"
GENESIS_PLUS_GX_MD_CHANNEL_4_VOLUME_INFO_0 "Reduz o volume do FM do Mega Drive do canal 4. Só funciona com o emulador de FM do MAME."
GENESIS_PLUS_GX_MD_CHANNEL_5_VOLUME_LABEL "% do volume do FM do Mega Drive do canal 5"
GENESIS_PLUS_GX_MD_CHANNEL_5_VOLUME_INFO_0 "Reduz o volume do FM do Mega Drive do canal 5. Só funciona com o emulador de FM do MAME."
GENESIS_PLUS_GX_SMS_FM_CHANNEL_0_VOLUME_LABEL "% do volume do som FM do Master System (YM2413) do canal 0"
GENESIS_PLUS_GX_SMS_FM_CHANNEL_0_VOLUME_INFO_0 "Reduz o volume do som FM do Master System do canal 0."
GENESIS_PLUS_GX_SMS_FM_CHANNEL_1_VOLUME_LABEL "% do volume do som FM do Master System (YM2413) do canal 1"
GENESIS_PLUS_GX_SMS_FM_CHANNEL_1_VOLUME_INFO_0 "Reduz o volume do som FM do Master System do canal 1."
GENESIS_PLUS_GX_SMS_FM_CHANNEL_2_VOLUME_LABEL "% do volume do som FM do Master System (YM2413) do canal 2"
GENESIS_PLUS_GX_SMS_FM_CHANNEL_2_VOLUME_INFO_0 "Reduz o volume do som FM do Master System do canal 2."
GENESIS_PLUS_GX_SMS_FM_CHANNEL_3_VOLUME_LABEL "% do volume do som FM do Master System (YM2413) do canal 3"
GENESIS_PLUS_GX_SMS_FM_CHANNEL_3_VOLUME_INFO_0 "Reduz o volume do som FM do Master System do canal 3."
GENESIS_PLUS_GX_SMS_FM_CHANNEL_4_VOLUME_LABEL "% do volume do som FM do Master System (YM2413) do canal 4"
GENESIS_PLUS_GX_SMS_FM_CHANNEL_4_VOLUME_INFO_0 "Reduz o volume do som FM do Master System do canal 4."
GENESIS_PLUS_GX_SMS_FM_CHANNEL_5_VOLUME_LABEL "% do volume do som FM do Master System (YM2413) do canal 5"
GENESIS_PLUS_GX_SMS_FM_CHANNEL_5_VOLUME_INFO_0 "Reduz o volume do som FM do Master System do canal 5."
GENESIS_PLUS_GX_SMS_FM_CHANNEL_6_VOLUME_LABEL "% do volume do som FM do Master System (YM2413) do canal 6"
GENESIS_PLUS_GX_SMS_FM_CHANNEL_6_VOLUME_INFO_0 "Reduz o volume do som FM do Master System do canal 6."
GENESIS_PLUS_GX_SMS_FM_CHANNEL_7_VOLUME_LABEL "% do volume do som FM do Master System (YM2413) do canal 7"
GENESIS_PLUS_GX_SMS_FM_CHANNEL_7_VOLUME_INFO_0 "Reduz o volume do som FM do Master System do canal 7."
GENESIS_PLUS_GX_SMS_FM_CHANNEL_8_VOLUME_LABEL "% do volume do som FM do Master System (YM2413) do canal 8"
GENESIS_PLUS_GX_SMS_FM_CHANNEL_8_VOLUME_INFO_0 "Reduz o volume do som FM do Master System do canal 8."
