GENESIS_PLUS_GX_SYSTEM_HW_LABEL "Sistem Donanımı"
GENESIS_PLUS_GX_SYSTEM_HW_INFO_0 "Yüklenen içeriği belirli bir öykünmüş konsolla çalıştırır. 'Otomatik' mevcut oyun için en uygun sistemi seçecektir."
OPTION_VAL_AUTO "Otomatik"
OPTION_VAL_SG_1000 "SG-1000"
OPTION_VAL_SG_1000_II "SG-1000 II"
OPTION_VAL_MARK_III "Mark III"
OPTION_VAL_MASTER_SYSTEM "Master System"
OPTION_VAL_MASTER_SYSTEM_II "Master System II"
OPTION_VAL_GAME_GEAR "Game Gear"
OPTION_VAL_MEGA_DRIVE_GENESIS "Mega Drive/Genesis"
GENESIS_PLUS_GX_REGION_DETECT_LABEL "Sistem Bölgesi"
GENESIS_PLUS_GX_REGION_DETECT_INFO_0 "Sistemin hangi bölgeden olduğunu belirtin. Game Gear dışındaki konsollar için 'PAL' 50hz, 'NTSC' 60hz'dir. Yanlış bölge seçiliyse, oyunlar normalden daha hızlı veya daha yavaş çalışabilir."
OPTION_VAL_NTSC_U "NTSC-U"
OPTION_VAL_PAL "PAL"
OPTION_VAL_NTSC_J "NTSC-J"
GENESIS_PLUS_GX_FORCE_DTACK_LABEL "Sistem Kilidi"
GENESIS_PLUS_GX_FORCE_DTACK_INFO_0 "Geçersiz adres erişimi gerçekleştirirken gerçek donanımda meydana gelen sistem kilitlemelerine öykünün. Bu, yalnızca doğru işlem için yasadışı davranışa dayanan belirli demolar ve homebrew oynatılırken devre dışı bırakılmalıdır."
OPTION_VAL_ENABLED "Etkinleştir"
OPTION_VAL_DISABLED "Devre Dışı"
GENESIS_PLUS_GX_BIOS_LABEL "Sistem Önyükleme ROM'u"
GENESIS_PLUS_GX_BIOS_INFO_0 "RetroArch'ın sistem dizininde varsa, öykünülmüş donanım için resmi BIOS/önyükleyici kullanın. Konsola özgü başlangıç sırası/animasyonu görüntüler, ardından yüklü içeriği çalıştırır."
GENESIS_PLUS_GX_BRAM_LABEL "CD Sistemi BRAM'i"
GENESIS_PLUS_GX_BRAM_INFO_0 "Sega CD içeriği çalıştırılırken, belirli bir bölgedeki tüm oyunlar arasında (BIOS başına) tek bir kayıt dosyasının paylaşılmasını mı yoksa her oyun için ayrı bir kayıt dosyası oluşturup oluşturmamayı (Oyun Başına) belirtir. Sega CD'sinin sınırlı bir dahili depolama alanına sahip olduğunu ve yalnızca bir avuç başlık için yeterli olduğunu unutmayın. Boşluktan kaçınmak için 'Oyun Başına' ayarı önerilir."
OPTION_VAL_PER_BIOS "BIOS Başına"
OPTION_VAL_PER_GAME "Oyun Başına"
GENESIS_PLUS_GX_ADDR_ERROR_LABEL "68K Adres Hatası"
GENESIS_PLUS_GX_ADDR_ERROR_INFO_0 "Genesis CPU (Motorola 68000), hizalanmamış hafıza erişimi gerçekleştirmeye çalışırken bir Adres Hatası (kilitlenme) üretir. '68K Adres Hatası' özelliğini etkinleştirmek bu davranışı simüle eder. ROM hacklerini oynarken sadece devre dışı bırakılmalıdır, çünkü bunlar daha az doğru emülatörler kullanılarak geliştirilir ve doğru işlem için geçersiz RAM erişimine güvenebilir."
GENESIS_PLUS_GX_LOCK_ON_LABEL "Kartuş Kilitleme"
GENESIS_PLUS_GX_LOCK_ON_INFO_0 "Kilitleme Teknolojisi, eski bir oyunun genişletilmiş veya değiştirilmiş bir oyun için özel bir kartuşun geçiş portuna bağlanmasına izin veren bir Genesis özelliğidir. Bu seçenek, hangi tür 'özel kilitleme' kartuşunun taklit edileceğini belirler. RetroArch'ın sistem dizininde ilgili bir bios dosyası bulunmalıdır."
OPTION_VAL_GAME_GENIE "Game Genie"
OPTION_VAL_ACTION_REPLAY_PRO "Action Replay (Pro)"
OPTION_VAL_SONIC_KNUCKLES "Sonic & Knuckles"
GENESIS_PLUS_GX_YM2413_LABEL "Master System FM (YM2413)"
GENESIS_PLUS_GX_YM2413_INFO_0 "Gelişmiş ses çıkışı için bazı Sega Mark III / Master System oyunları tarafından kullanılan FM Ses Ünitesinin emülasyonunu etkinleştirin."
GENESIS_PLUS_GX_YM2612_LABEL "Mega Drive / Genesis FM"
GENESIS_PLUS_GX_YM2612_INFO_0 "Mega Drive / Genesis'in FM sentezleyicisini (ana ses üreteci) taklit etmek için kullanılan yöntemi seçin. 'MAME' seçenekleri hızlı ve çoğu sistemde tam hızda çalışıyor. 'Nuke' seçenekleri döngüde doğrudur, çok kaliteli ve önemli CPU gereksinimlerine sahiptir. 'YM2612' yongası, orijinal Model 1 Genesis tarafından kullanılır. 'YM3438' daha sonra Genesis revizyonlarında kullanılır."
GENESIS_PLUS_GX_YM2612_INFO_1 "Mega Drive / Genesis'in FM sentezleyicisini (ana ses üreteci) taklit etmek için kullanılan yöntemi seçin. 'YM2612' yongası, orijinal Model 1 Genesis tarafından kullanılır. 'YM3438' daha sonra Genesis revizyonlarında kullanılır."
OPTION_VAL_MAME_YM2612 "MAME (YM2612)"
OPTION_VAL_MAME_ASIC_YM3438 "MAME (ASIC YM3438)"
OPTION_VAL_MAME_ENHANCED_YM3438 "MAME (Enhanced YM3438)"
OPTION_VAL_NUKED_YM2612 "Nuked (YM2612)"
OPTION_VAL_NUKED_YM3438 "Nuked (YM3438)"
GENESIS_PLUS_GX_SOUND_OUTPUT_LABEL "Ses Çıkışı"
GENESIS_PLUS_GX_SOUND_OUTPUT_INFO_0 "Stereo veya mono ses üretimini seçin."
OPTION_VAL_STEREO "Stereo"
OPTION_VAL_MONO "Mono"
GENESIS_PLUS_GX_PSG_PREAMP_LABEL "PSG Preamp Level"
GENESIS_PLUS_GX_PSG_PREAMP_INFO_0 "Master System, Game Gear ve Genesis'de bulunan öykünmüş SN76496 4 kanallı Programlanabilir Ses Üretecinin ses ön yükselticisi seviyesini ayarlayın."
GENESIS_PLUS_GX_FM_PREAMP_LABEL "FM Preamp Level"
GENESIS_PLUS_GX_FM_PREAMP_INFO_0 "Öykünülmüş Sega Mark III/Master System FM Ses Ünitesinin ses ön yükselticisi seviyesini ayarlayın."
GENESIS_PLUS_GX_AUDIO_FILTER_LABEL "Ses Filtresi"
GENESIS_PLUS_GX_AUDIO_FILTER_INFO_0 "Model 1 Genesis'in karakteristik sesini daha iyi simüle etmek için düşük geçişli bir ses filtresini etkinleştirin."
OPTION_VAL_LOW_PASS "Low-Pass"
GENESIS_PLUS_GX_LOWPASS_RANGE_LABEL "Low-Pass Filtresi %"
GENESIS_PLUS_GX_LOWPASS_RANGE_INFO_0 "Düşük ses geçiş filtresinin kesme frekansını belirtin. Daha yüksek bir değer, yüksek frekans spektrumunun daha geniş bir aralığı azaltıldığı için filtrenin algılanan gücünü arttırır."
GENESIS_PLUS_GX_AUDIO_EQ_LOW_LABEL "EQ Low"
GENESIS_PLUS_GX_AUDIO_EQ_LOW_INFO_0 "Dahili ses ekolayzırın düşük aralık bandını ayarlayın."
GENESIS_PLUS_GX_AUDIO_EQ_MID_LABEL "EQ Mid"
GENESIS_PLUS_GX_AUDIO_EQ_MID_INFO_0 "Dahili ses ekolayzerinin orta aralık bandını ayarlayın."
GENESIS_PLUS_GX_AUDIO_EQ_HIGH_LABEL "EQ High"
GENESIS_PLUS_GX_AUDIO_EQ_HIGH_INFO_0 "Dahili ses ekolayzerinin yüksek aralık bandını ayarlayın."
GENESIS_PLUS_GX_BLARGG_NTSC_FILTER_LABEL "Blargg NTSC Filtresi"
GENESIS_PLUS_GX_BLARGG_NTSC_FILTER_INFO_0 "Çeşitli NTSC TV sinyallerini taklit etmek için bir video filtresi uygulayın."
OPTION_VAL_MONOCHROME "Monochrome"
OPTION_VAL_COMPOSITE "Composite"
OPTION_VAL_SVIDEO "S-Video"
OPTION_VAL_RGB "RGB"
GENESIS_PLUS_GX_LCD_FILTER_LABEL "LCD Gölgelenme Filtresi"
GENESIS_PLUS_GX_LCD_FILTER_INFO_0 "Game Gear ve 'Genesis Nomad' LCD panellerinin ekran özelliklerini taklit etmek için bir görüntü “gölgelenme” filtresi uygulayın."
GENESIS_PLUS_GX_OVERSCAN_LABEL "Çerçeveler"
GENESIS_PLUS_GX_OVERSCAN_INFO_0 "Aşırı tarama bölgelerini ekranın üstünde/altında ve/veya sol/sağında görüntülemek için bunu etkinleştirin. Bunlar normalde standart tanımlı bir televizyonun kenarındaki çerçeve tarafından gizlenir."
OPTION_VAL_TOP_BOTTOM "Üstünde/Atında"
OPTION_VAL_LEFT_RIGHT "Sol/Sağ"
OPTION_VAL_FULL "Tam"
GENESIS_PLUS_GX_GG_EXTRA_LABEL "Game Gear Genişletilmiş Ekran"
GENESIS_PLUS_GX_GG_EXTRA_INFO_0 "Game Gear oyunlarını 256x192 çözünürlüğe sahip 'SMS' modunda çalıştırmaya zorlar. Ek içerik gösterebilir, ancak genellikle bozuk/istenmeyen resim verilerinin kenarlığını görüntüler."
GENESIS_PLUS_GX_ASPECT_RATIO_LABEL "Çekirdek Tarafından Sağlanan En Boy Oranı"
GENESIS_PLUS_GX_ASPECT_RATIO_INFO_0 "Tercih edilen içerik en boy oranını seçin. Bu, yalnızca RetroArch’ın en boy oranı Video ayarlarında 'Çekirdek Tarafından Sağlanan' olarak ayarlandığında uygulanacaktır."
OPTION_VAL_NTSC_PAR "NTSC PAR"
OPTION_VAL_PAL_PAR "PAL PAR"
GENESIS_PLUS_GX_RENDER_LABEL "Geçmeli Mod 2 Çıkışı"
GENESIS_PLUS_GX_RENDER_INFO_0 "Geçmeli Mod 2, Genesis'e, her kareye alternatif tarama çizgileri çizerek (bu, 'Sonic the Hedgehog 2' ve 'Savaş Arabaları' çok oyunculu modları tarafından kullanılır) çift yükseklikte (yüksek çözünürlüklü) 320x448 görüntü vermesini sağlar. 'Çift Alan' orijinal donanımı taklit eder, titreyen/birbirine geçen eserler ile keskin bir görüntü oluşturur. 'Tek Alan', görüntüyü dengeleyen ancak hafif bulanıklığa neden olan, birbirinin yerine geçen bir filtredir."
OPTION_VAL_SINGLE_FIELD "Tek Alan"
OPTION_VAL_DOUBLE_FIELD "Çift Alan"
GENESIS_PLUS_GX_GUN_CURSOR_LABEL "Light Gun Göstergesini Göster"
GENESIS_PLUS_GX_GUN_CURSOR_INFO_0 "'MD Menacer', 'MD Justifiers' ve 'MS Light Phaser' giriş cihazı tiplerini kullanırken Light Gun göstergelerini gösterin."
GENESIS_PLUS_GX_GUN_INPUT_LABEL "Light Gun Girdisi"
GENESIS_PLUS_GX_GUN_INPUT_INFO_0 "Fare kontrollü 'Light Gun' veya 'Dokunmatik Ekran' girişi kullanın."
OPTION_VAL_LIGHTGUN "Light Gun"
OPTION_VAL_TOUCHSCREEN "Dokunmatik Ekran"
GENESIS_PLUS_GX_INVERT_MOUSE_LABEL "Fare Y Eksenini Ters Çevir"
GENESIS_PLUS_GX_INVERT_MOUSE_INFO_0 "'MD Fare' giriş cihazı türünün Y eksenini ters çevirir."
GENESIS_PLUS_GX_OVERCLOCK_LABEL "CPU Hızı"
GENESIS_PLUS_GX_OVERCLOCK_INFO_0 "Öykünülmüş CPU hız aşırtması. Yavaşlamayı azaltabilir, ancak aksaklığa neden olabilir."
OPTION_VAL_100 "100%"
OPTION_VAL_125 "125%"
OPTION_VAL_150 "150%"
OPTION_VAL_175 "175%"
OPTION_VAL_200 "200%"
GENESIS_PLUS_GX_NO_SPRITE_LIMIT_LABEL "Satır Başına Sprite Limitini Kaldır"
GENESIS_PLUS_GX_NO_SPRITE_LIMIT_INFO_0 "8 (Ana Sistem) veya 20 (Genesis) tarama başına sprite donanım sınırını kaldırır. Bu, titremeyi azaltır ancak bazı oyunlar özel efektler oluşturmak için donanım sınırını kullandığı için görsel hatalara neden olabilir."
