# Download translations form Crowdin & Recreate libretro_core_options_intl.h

name: Crowdin Translation Integration

on:
  schedule:
    - cron: '0 0 * * *'  # every day at midnight

jobs:
  create_intl_file:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v2

      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
          fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.

      - name: Create intl file
        shell: bash
        env:
          CROWDIN_API_KEY: ${{ secrets.CROWDIN_API_KEY }}
        run: |
          python3 intl/crowdin_translation_download.py "$CROWDIN_API_KEY" "Core_options"
          python3 intl/crowdin_translate.py "libretro"

      - name: Commit files
        run: |
          git config --local user.email "github-actions@github.com"
          git config --local user.name "github-actions[bot]"
          git add <path/to/libretro_core_options_intl.h file>
          git commit -m "Fetch translations & Recreate libretro_core_options_intl.h" -a

      - name: GitHub Push
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
